[book]
title = "mdBook test book"
description = "A demo book to test and validate changes"
authors = ["Alex Mikhalev"]
language = "en"
logo = "/img/terraphim_gray.png"
github_url = "https://github.com/terraphim/md-book"
# Find the edit url base by navigating to the page on GitHub, hit "Edit" button and copying the URL
github_edit_url_base = "https://github.com/terraphim/terraphim-ai/edit/main/docs/src/"

[paths]
# Optional: Custom templates directory (defaults to "templates")
templates = "src/templates"

[paths]
# Optional: Custom templates directory (defaults to "templates")
templates = "src/templates"

[rust]
# Rust related features are not implemented yet
edition = "2018"
[markdown]
format = "markdown"  # mdx or "gfm" or "markdown"
frontmatter = false # not implemented

[output.html]
mathjax-support = true # not implemented
allow_html = true

[output.html.playground] # not implemented
editable = true
line-numbers = true

[output.html.search] # not implemented
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

