name: md-book
region: nyc

static_sites:
  - name: web
    github:
      repo: terraphim/md-book
      branch: main
      deploy_on_push: true
    build_command: cargo run -- -i test_input -o dist
    output_dir: dist
    routes:
      - path: /
    environment_slug: rust
    envs:
      - key: RUST_VERSION
        value: "1.70.0"
    cors:
      allow_origins:
        - prefix: https://
      allow_methods:
        - GET
        - OPTIONS
        - POST
        - PUT
        - DELETE
      allow_headers:
        - Content-Type
        - Authorization
      max_age: 600
